# Generated by Django 3.2.8 on 2021-10-13 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basketball_ms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_score', models.IntegerField(null=True)),
                ('team2_score', models.IntegerField(null=True)),
                ('game_round_number', models.CharField(choices=[('FR', 'First round'), ('SR', 'Second round'), ('TR', 'Third round'), ('W', 'Winner')], default='FR', max_length=2)),
                ('team1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='basketball_ms.team')),
                ('team2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='basketball_ms.team')),
            ],
        ),
        migrations.AddField(
            model_name='playerstatus',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basketball_ms.game'),
        ),
        migrations.AddField(
            model_name='teamstatus',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basketball_ms.game'),
        ),
    ]
